// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJb29ocZMFFp6QtyOpOfymTIp8-G6coyI',
    appId: '1:436894648629:web:35405837004a8a6b99a47c',
    messagingSenderId: '436894648629',
    projectId: 'easy-project-47053',
    authDomain: 'easy-project-47053.firebaseapp.com',
    storageBucket: 'easy-project-47053.appspot.com',
    measurementId: 'G-3N6FXFLRRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUAz_wNxwr856JnNFEiRMz9fbuowSTZrk',
    appId: '1:436894648629:android:54bb918c1e77b6de99a47c',
    messagingSenderId: '436894648629',
    projectId: 'easy-project-47053',
    storageBucket: 'easy-project-47053.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZZ3x-R0WcSbnTTsSjbq9tWSwujTu1QnA',
    appId: '1:436894648629:ios:5c2561e9a461dac899a47c',
    messagingSenderId: '436894648629',
    projectId: 'easy-project-47053',
    storageBucket: 'easy-project-47053.appspot.com',
    iosClientId: '436894648629-4fnsk8o5kcmakhgbol34shocoqkep83h.apps.googleusercontent.com',
    iosBundleId: 'dev.man4s.easyProject',
  );
}
